kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: image-controller
subjects:
- kind: ServiceAccount
  name: image-controller
roleRef:
  kind: Role
  name: image-controller
  apiGroup: rbac.authorization.k8s.io
